### ISSUE TITLE
How to reference the element of an array variable in bosh.yml?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-deployment#137]
I have an array variable defined in the variable YAML file:
```
key:
- val1
- val2
```

How can I reference the array element (like val1) in bosh.yml? I tried `((key.0))` but it doesn't work.

**Comment by cppforlife** [comment]
@gu-bin there is no way to reference arrays as variables. do you mind giving an example where this is useful?

**Comment by gu-bin** [comment]
@cppforlife This is a sample got from our existing variable YML files which lists the datacenters and vlans that are used in an environments:
```
  data_center_name:
  - dal06
  - dal09
  - dal05
  - dal10
  private_vlan_id:
  - id11
  - id12
  - id13
  - id14
  public_vlan_id:
  - id21
  - id22
  - id23
  - id24
```
The director will use the first elements (dal06, id11, id21) and the CF deployment will use all of them. There are many other array variables as well and I can't list them all.

We have more than one hundred staging/production environments and each environment has several variable files. So it's very hard to change all the array variables to simple key/value. Would you please put it into plan so that we can reference the array elements as variable? Thanks.
