### ISSUE TITLE
Please provide an ops file for forwarding connections to bosh-lite

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/bosh-deployment#16]
It is useful to be able to forward connections to bosh-lite when deploying a bosh-lite on an IaaS (e.g. bosh-lite on GCP) so you can test against the bosh-lite directly.  There seems to be a networking-release for bosh that enables this kind of port forwarding.  It would be nice if bosh-deployment included an ops file that did this port forwarding for you.  I believe that the following should be sufficient:

```
- type: replace
  path: /releases/-
  value:
    name: networking
    sha1: 092a6e0649e5adb88ec947b0d37d3e5afebe68fe
    url: https://bosh.io/d/github.com/cloudfoundry/networking-release?v=8
    version: 8

- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value:
    name: port_forwarding
    release: networking-release

- type: replace
  path: /instance_groups/name=bosh/properties/networking?/port_forwarding?
  value:
  - external_port: 80
    internal_ip: 10.244.0.34
    internal_port: 80
  - external_port: 443
    internal_ip: 10.244.0.34
    internal_port: 443
  - external_port: 2222
    internal_ip: 10.244.0.34
    internal_port: 2222
  - external_port: 4443
    internal_ip: 10.244.0.34
    internal_port: 4443

```
