### ISSUE TITLE
include backup-and-restore-sdk release to allow bbr to succeed

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-deployment#192]
potentially need to include bbr user as well

**Comment by lancefrench** [comment]
Not sure where you'd want to drop this in, but the following ops-file worked for me.  In working with a `bbl` deployed director, the `jumpbox` user had sufficient permissions to dump the credhub postgres.  Version `1.1.0` was chosen because it was the first version that contained the needed Postgres tooling.  Newer versions add more stuff and are getting large, so I figured just grab what was needed.

```
- type: replace 
  path: /releases/-
  value: 
    name: backup-and-restore-sdk
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/backup-and-restore-sdk-release?v=1.1.0
    sha1: 3ead0c752ce5a63a8453de35fff452661d2cd6b7
    version: 1.1.0

- type: replace 
  path: /instance_groups/name=bosh/jobs/name=database-backup-restorer?
  value: 
    name: database-backup-restorer
    release: backup-and-restore-sdk
    properties: {}
```
