### ISSUE TITLE
 getsockopt: no route to host While Bosh create env 

### ISSUE THREAD

**Issue by kumarganesh2814** [cloudfoundry/bosh-deployment#196]
Hi Team,

I am trying to setup bosh env as below commands

```

bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/vsphere/cpi.yml \
    -v director_name=bosh-1 \
    -v internal_cidr=10.112.79.1/24 \
    -v internal_gw=10.112.79.1 \
    -v internal_ip=10.112.xx.xxx \
    -v network_name="VM Network" \
    -v vcenter_dc=AppOps_BLR_Datacenter \
    -v vcenter_ds=Host1_DS_1 \
    -v vcenter_ip=10.112.76.00 \
    -v vcenter_user=user \
    -v vcenter_password=pass \
    -v vcenter_templates=centos-7-mysql \
    -v vcenter_vms=bosh-1-vms \
    -v vcenter_disks=bosh-1-disks \
    -v vcenter_cluster=AppOps_KM_Cluster
```

But at last step of deployment I am getting error as below:

```

Started deploying
  Waiting for the agent on VM 'vm-88c91e47-1cf5-4e41-b53e-04fe0d905bbc'... Failed (00:00:12)
  Deleting VM 'vm-88c91e47-1cf5-4e41-b53e-04fe0d905bbc'... Finished (00:00:12)
  Creating VM for instance 'bosh/0' from stemcell 'sc-1fc4ee58-97d2-4f46-8a24-0e5064f9b812'... Finished (00:00:15)
  Waiting for the agent on VM 'vm-2316a4a8-dd10-4ef8-86b0-170be8a0d112' to be ready... Failed (00:10:01)
Failed deploying (00:10:44)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@10.112.79.121:6868/agent: dial tcp 10.112.79.121:6868: getsockopt: no route to host

Exit code 1

```

Can you please advise on this error. We are not using any proxy. Able to connect all internet sites.

Best Regards
Ganesh Kumar

**Comment by dpb587-pivotal** [comment]
This is a duplicate discussion from [cloudfoundry#general](https://cloudfoundry.slack.com/archives/C02FL4A2K/p1519210396000510) and sounds like it's due to [misconfigured network settings](https://cloudfoundry.slack.com/archives/C02FL4A2K/p1519224734000458). Can keep this open briefly until it's confirmed.

**Comment by kumarganesh2814** [comment]
@dpb587-pivotal Yes it was wrong config for Network got it resolved by changing host storage on same esxi host as where bosh is deployed.

Best Regards
Ganesh Kumar

**Comment by kumarganesh2814** [comment]
@dpb587-pivotal 
I have created few VM using example https://github.com/cppforlife/zookeeper-release

Can you please advise how I can ssh to those VM 

I tried with vcap user and default password but it doesnt work in sample manifest also there is no password regarding same.

Can you please advise how we can ssh to bosh vms or even I am not able to ssh to bosh director VM 

```
---
name: bosh

releases:
- name: bosh
  version: "264.7.0"
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-264.7.0-ubuntu-trusty-3468.21-20180125-031202-579399892-20180125031207.tgz?versionId=gnR.RVKDRH_Vk63jxsGBOhcHOZ9p8qCJ
  sha1: 3850c68124bf5bce3cfb1433cce52e2d67741d94

resource_pools:
- name: vms
  network: default
  env:
    bosh:
      password: 'Vmware.123'
      mbus:
        cert: ((mbus_bootstrap_ssl))

disk_pools:
- name: disks
  disk_size: 65_536

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    static: [((internal_ip))]
    dns: [10.112.64.1,10.112.64.2]

instance_groups:
- name: bosh
  instances: 1
  jobs:
  - {name: nats, release: bosh}
  - {name: postgres-9.4, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  resource_pool: vms
  persistent_disk_pool: disks
  networks:
  - name: default
    static_ips: [((internal_ip))]
  properties:
    nats:
      address: ((internal_ip))
      user: nats
      password: ((nats_password))
      tls:
        ca: ((nats_server_tls.ca))
        client_ca:
          certificate: ((nats_ca.certificate))
          private_key: ((nats_ca.private_key))
        server:
          certificate: ((nats_server_tls.certificate))
          private_key: ((nats_server_tls.private_key))
        director:
          certificate: ((nats_clients_director_tls.certificate))
          private_key: ((nats_clients_director_tls.private_key))
        health_monitor:
          certificate: ((nats_clients_health_monitor_tls.certificate))
          private_key: ((nats_clients_health_monitor_tls.private_key))
    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: ((postgres_password))
      database: bosh
      adapter: postgres
    blobstore:
      address: ((internal_ip))
      port: 25250
      provider: dav
      director:
        user: director
        password: ((blobstore_director_password))
      agent:
        user: agent
        password: ((blobstore_agent_password))
    director:
      address: 127.0.0.1
      name: ((director_name))
      db: *db
      flush_arp: true
      enable_post_deploy: true
      generate_vm_passwords: true
      enable_dedicated_status_worker: true
      enable_nats_delivered_templates: true
      workers: 4
      local_dns:
        enabled: true
      events:
        record_events: true
      ssl:
        key: ((director_ssl.private_key))
        cert: ((director_ssl.certificate))
      user_management:
        provider: local
        local:
          users:
          - name: admin
            password: ((admin_password))
          - name: hm
            password: ((hm_password))
    hm:
      director_account:
        user: hm
        password: ((hm_password))
        ca_cert: ((director_ssl.ca))
      resurrector_enabled: true
    ntp: &ntp
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    agent:
      mbus: nats://nats:((nats_password))@((internal_ip)):4222

cloud_provider:
  mbus: https://mbus:((mbus_bootstrap_password))@((internal_ip)):6868
  cert: ((mbus_bootstrap_ssl))
  properties:
    agent: {mbus: "https://mbus:((mbus_bootstrap_password))@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp

variables:
- name: admin_password
  type: password
- name: blobstore_director_password
  type: password
- name: blobstore_agent_password
  type: password
- name: hm_password
  type: password
- name: mbus_bootstrap_password
  type: password
- name: nats_password
  type: password
- name: postgres_password
  type: password

- name: default_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca

- name: mbus_bootstrap_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: ((internal_ip))
    alternative_names: [((internal_ip))]

- name: director_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: ((internal_ip))
    alternative_names: [((internal_ip))]

- name: nats_ca
  type: certificate
  options:
    is_ca: true
    common_name: default.nats-ca.bosh-internal

- name: nats_server_tls
  type: certificate
  options:
    ca: nats_ca
    common_name: default.nats.bosh-internal
    alternative_names: [((internal_ip))]
    extended_key_usage:
    - server_auth

- name: nats_clients_director_tls
  type: certificate
  options:
    ca: nats_ca
    common_name: default.director.bosh-internal
    extended_key_usage:
    - client_auth

- name: nats_clients_health_monitor_tls
  type: certificate
  options:
    ca: nats_ca
    common_name: default.hm.bosh-internal
    extended_key_usage:
    - client_auth
```

Above is my bosh.yml used to create bosh env

Best Regards
Ganesh

**Comment by dpb587-pivotal** [comment]
I'd recommend reviewing [this tutorial](http://mariash.github.io/learn-bosh/) for a few more details on how you can use the BOSH CLI. Specifically, to SSH, you should use the `bosh ssh` command.

For deploying director, I'd recommend you start with [cloudfoundry/bosh-deployment](https://github.com/cloudfoundry/bosh-deployment), and that repository includes an example of how you add direct SSH support (via [jumpbox user](https://bosh.io/docs/jumpbox) to the director.

**Comment by kumarganesh2814** [comment]
@dpb587-pivotal 

Thanks 

But while following 

Getting below error 

```
Task 54 | 03:30:49 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
Task 54 | 03:30:49 | Preparing deployment: Preparing deployment (00:00:00)
                   L Error: Instance group 'app' with network 'default' declares static ip '10.112.76.120', which belongs to no subnet
Task 54 | 03:30:49 | Error: Instance group 'app' with network 'default' declares static ip '10.112.76.120', which belongs to no subnet

Task 54 Started  Fri Mar  9 03:30:49 UTC 2018
Task 54 Finished Fri Mar  9 03:30:49 UTC 2018
Task 54 Duration 00:00:00
Task 54 error

Updating deployment:
  Expected task '54' to succeed but state is 'error'

Exit code 1
```

This Static IP is this is something we have to get from network team or we can define ourself

My Manifest Yaml looks like this.

```
---
name: learn-bosh

releases:
- name: learn-bosh
  version: latest

networks:
- name: default
  subnets:
  - range: 10.112.76.0/22
    dns: [10.112.166.138,10.112.16.130]
    gateway: 10.112.79.253
    reserved: [10.112.76.120]
    static: [10.112.76.251,10.112.76.252,10.112.76.253]

resource_pools:
- name: default
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest
  network: default

compilation:
  workers: 2
  network: default

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
- name: app
  templates:
  - name: app
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.112.76.120
  properties: {}
```

Output of route -n

```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.112.79.253   0.0.0.0         UG    100    0        0 ens192
10.112.76.0     0.0.0.0         255.255.252.0   U     100    0        0 ens192
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
```

I have deployed my bosh env on vsphere.

Best Regards
Ganesh Kumar
