### ISSUE TITLE
bosh-deployment for vSphere doesn't support 

### ISSUE THREAD

**Issue by haydonryan** [cloudfoundry/bosh-deployment#219]
[https://github.com/cloudfoundry/bosh-deployment/blob/master/vsphere/cpi.yml#L57](https://github.com/cloudfoundry/bosh-deployment/blob/master/vsphere/cpi.yml#L57)
Only allows the configuration of one Cluster.  While this is ok for bosh. We ran into an issue at a customer where there they are deploying for 3azs (ie multiple clusters). 

It's quite difficult to determine what the problem is from bosh's error (can't find matching datastore).

Any chance of a multiple-cluster vsphere cpi.yml?

**Comment by dpb587-pivotal** [comment]
@yeshwantbabar is there any documentation around using multiple clusters, or troubleshooting errors about matching datastores? Googling hasn't been helpful to me yet.

**Comment by schmidtsv** [comment]
One advice. On cloud_provider you have to define the cluster the Director goes to, on the cpi block of the bosh director you can use an array like this:
```yaml
      - clusters:
        - C01
        - C02
        - C03
```

**Comment by giner** [comment]
@haydonryan, I think you need to use your own cloud-config with AZs configured for different clusters https://github.com/cloudfoundry/bosh-deployment/blob/master/vsphere/cloud-config.yml

**Comment by schmidtsv** [comment]
@giner that will not help there.
The director will only deploy to clusters specified in the config of the CPI (aka the array of clusters there) if you define other clusters in your cloud-config, those will be ignored by bosh.

**Comment by haydonryan** [comment]
@schmidtsv is correct - we originally tried that @giner, but it failed.

**Comment by giner** [comment]
@schmidtsv, we are specifying 3 clusters in CPI and one per AZ in cloud config. It works for us.

CPI:
```
vcenter:
...
  datacenters:
  - name: dc1
    clusters:
    - cluster1
    - cluster2
    - cluster3
```
Cloud Config:
```
azs:
- name: z1
  cloud_properties:
    datacenters:
    - name: dc1
      clusters:
      - cluster1: {}

- name: z2
  cloud_properties:
    datacenters:
    - name: dc1
      clusters:
      - cluster2: {}

- name:z3
  cloud_properties:
    datacenters:
    - name: dc1
      clusters:
      - cluster3: {}
```
