### ISSUE TITLE
External database for UAA and credhub

### ISSUE THREAD

**Issue by Ykisialiou** [cloudfoundry/bosh-deployment#229]
Hello. Sorry, is there any reason,why credhub and UAA ops-files has hardcoded
```
properties:
  credhub:
    data_storage:
      host: 127.0.0.1
```
```
properties:
  uaadb:
    address: 127.0.0.1
```
Probably it's better have a variable here to simplify external DB usage?
