### ISSUE TITLE
AWS S3 for blobstore broken with latest release?

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry/bosh-deployment#254]
Since updating to latest `bosh-deployment` earlier today I see errors like this appearing during compilation steps:

```
Task 50858 | 09:20:22 | Compiling packages: routing_utils/34ffc6f79ae2d40b294dab9a33daab724c0c6df4 (00:02:08)
                     L Error: Action Failed get_task: Task 300c812e-d688-4aaf-42f5-21efaf0e1244 result: Compiling package routing_utils: Fetching package routing_utils: Fetching package blob 15749007-7f42-4200-9854-6ab8ded03ccf: Getting blob from inner blobstore: Getting blob from inner blobstore: Shelling out to bosh-blobstore-dav cli: Running command: 'bosh-blobstore-dav -c /var/vcap/bosh/etc/blobstore-dav.json get 15749007-7f42-4200-9854-6ab8ded03ccf /var/vcap/data/tmp/bosh-blobstore-externalBlobstore-Get118171596', stdout: 'Error running app - Getting dav blob 15749007-7f42-4200-9854-6ab8ded03ccf: Get http://10.3.2.6:25250/6b/15749007-7f42-4200-9854-6ab8ded03ccf: dial tcp 10.3.2.6:25250: getsockopt: connection refused', stderr: '': exit status 1
```

Normally we don't run a blobstore server on 25250 - we instead had the following operator file:

```yaml
- type: replace
  path: /instance_groups/name=bosh/properties/blobstore
  value:
    provider: s3
    access_key_id: xxx
    secret_access_key: xxx
    bucket_name: xxx
    s3_region: xxx
```

It seems to at least partially be working, as I don't see any ports listening on 25250, however something seems to think we are running it...

I suspect the following commit caused these errors to start:
https://github.com/cloudfoundry/bosh-deployment/commit/ad3411b0c18701a4c948d638666533c45c22e63d

I'm going to experimenting with removing parts of that via the operator file. Alternate ideas welcome.

**Comment by aeijdenberg** [comment]
The relevant documentation appear to be here: https://bosh.io/docs/director-configure-blobstore/

I was able to add:

```yaml
- type: remove
  path: /instance_groups/name=bosh/properties/agent/env
```

to our operator file to get past the error listed above.

It's not clear to me if the docs need to be updated, or if the recent change isn't quite as expected?

(note the 3rd relevant part in our operator file is:

```yaml
- type: remove
  path: /instance_groups/name=bosh/jobs/name=blobstore
```
)

**Comment by evandbrown** [comment]
This broke BATS for us.

**Comment by voelzmo** [comment]
There is an ops-file enabling s3 agent blobstore which includes the line that @aeijdenberg mentions: https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/s3-blobstore.yml#L15

Is this not working for you, or is it just not discoverable and we should update documentation?

**Comment by voelzmo** [comment]
@evandbrown: the equivalent for google cloud also has a line to remove the DAV agent blobstore configuration https://github.com/cloudfoundry/bosh-deployment/blob/master/gcp/gcs-blobstore.yml#L13

**Comment by freddesbiens** [comment]
Validated that this is still an issue. Closing and reopening this story so that gitbot will create a corresponding tracker story.

**Comment by voelzmo** [comment]
> Validated that this is still an issue
@freddesbiens Are you saying that using an S3 blobstore doesn't work when using latest bosh-deployment and applying https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/s3-blobstore.yml#L15 ? My impression was this was working.

**Comment by freddesbiens** [comment]
I misread the thread. I had the (wrong) impression that the ops file was a workaround, not an actual fix. @aeijdenberg Does using the latest bosh-deployment with the https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/s3-blobstore.yml ops file work for you?

**Comment by aeijdenberg** [comment]
@freddesbiens - I don't think that operator file existed when I last looked at this, but I've taken it now and used that instead of our own and it seems to have worked.

One question though, why is the last section (ie below) needed:

```yaml
- type: replace
  path: /instance_groups/name=bosh/properties/agent/env/bosh/blobstores?/-
  value:
    provider: s3
    options:
      bucket_name: ((s3-bucket-name))
      access_key_id: ((s3-access-key-id))
      secret_access_key: ((s3-secret-access-key))
      region: ((s3-region))
```

Until just now, we simply didn't add that (we just removed the entire `/instance_groups/name=bosh/properties/agent/env`), and everything seemed to work OK.
