### ISSUE TITLE
Could you upload the stemcell image to cn-northwest-1?

### ISSUE THREAD

**Issue by Rydros** [cloudfoundry/bosh-deployment#273]
Currently the images just have to following regions available:

us-gov-west-1: ami-5361f732
    ap-northeast-1: ami-a29966dd
    ap-northeast-2: ami-ab14bcc5
    ap-south-1: ami-3c81ad53
    ap-southeast-1: ami-3bc0fd47
    ap-southeast-2: ami-15b56677
    ca-central-1: ami-3d3aba59
    eu-central-1: ami-10301bfb
    eu-west-1: ami-7f7d4406
    eu-west-2: ami-ad9478ca
    eu-west-3: ami-ce68d9b3
    sa-east-1: ami-6d306e01
    us-east-1: ami-8f9afdf0
    us-east-2: ami-85d3efe0
    us-west-1: ami-0c7e656c
    us-west-2: ami-47661f3f
    cn-north-1: ami-d105dbbc

** Example extracted from version light-bosh-stemcell-3586.16-aws-xen-hvm-ubuntu-trusty-go_agent

It would really be helpful. Thanks!

**Comment by dpb587-pivotal** [comment]
Thanks - we'll be tracking this work in [Story #158503787](https://www.pivotaltracker.com/story/show/158503787).

**Comment by jrussett** [comment]
Going to close this issue as we've been publishing light stemcells to `cn-northwest-1` since September.

e.g., from `light-bosh-stemcell-170.5-aws-xen-hvm-ubuntu-xenial-go_agent.tgz/stemcell.MF`:

```
---
name: bosh-aws-xen-hvm-ubuntu-xenial-go_agent
version: '170.5'
bosh_protocol: '1'
sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
operating_system: ubuntu-xenial
stemcell_formats:
- aws-light
cloud_properties:
  ami:
    us-gov-west-1: ami-36e68357
    ap-northeast-1: ami-0f24b194859a2b2ce
    ap-northeast-2: ami-046cdc2a44f8cd11b
    ap-south-1: ami-0c254c5728469884c
    ap-southeast-1: ami-0feed6c5b34d50c40
    ap-southeast-2: ami-00202119002231c81
    ca-central-1: ami-088a4d7ada337154a
    eu-central-1: ami-0ce57dc6e1121ab03
    eu-west-1: ami-051b094309d3af8e4
    eu-west-2: ami-06a229cebecbe4ba1
    eu-west-3: ami-04de5962a8093fdf1
    sa-east-1: ami-0bf04826c653abcc2
    us-east-1: ami-0f229395f95f6490f
    us-east-2: ami-01db65f19ea1272b4
    us-west-1: ami-0b312c13b491d7ec7
    us-west-2: ami-0b69af436b34ce2ae
    cn-northwest-1: ami-0492b3e1be7e504fc
    cn-north-1: ami-03bd762fd953b9de4
```
