### ISSUE TITLE
create-env  does not support changing certificate validity duration

### ISSUE THREAD

**Issue by addisflava** [cloudfoundry/bosh-deployment#373]
currently create-env  does not accept changing certificate duration at all 

```
Parsing release set manifest 'bosh.yml':
  Evaluating manifest:
    Getting all variables from variable definitions sections:
      Generating variable 'mbus_bootstrap_ssl':
        Failed to generate certificate, parameters are invalid:
          Unsupported certificate parameter 'duration'

Exit code 1

```
from the deployment 

```
variables:
- name: mbus_bootstrap_ssl
  options:
    alternative_names:
    - ((internal_ip))
    ca: default_ca
    common_name: ((internal_ip))
    duration: 3650

```

or 

```
Deployment manifest: 'bosh.yml'
Deployment state: 'bosh-state-8.json'

Started validating
Failed validating (00:00:05)

Parsing release set manifest 'bosh.yml':
  Evaluating manifest:
    Getting all variables from variable definitions sections:
      Generating variable 'blobstore_server_tls':
        Failed to generate certificate, parameters are invalid:
          Unsupported certificate parameter 'duration'

Exit code 1

```
```
- name: blobstore_server_tls
  options:
    alternative_names:
    - ((internal_ip))
    ca: blobstore_ca
    common_name: ((internal_ip))
    duration: 3650
```
