### ISSUE TITLE
Add variable for bosh DNS

### ISSUE THREAD

**Issue by zmb3** [cloudfoundry/bosh-deployment#89]
Can we make the DNS configurable in the bosh deployment like the rest of the network settings?
Google's public DNS generally doesn't work for on-prem deploys.

```yml
networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    static: [((internal_ip))]
    dns: [8.8.8.8]            # <--------
```
